spring:
  datasource:
    url: jdbc:mysql://middleware.inddbes.com:3306/ddbes_demo?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: ddbes
    password: ddbes2020
logging:
  level:
    com.ddbes.report: debug